server.port=8080

spring.data.mongodb.uri=mongodb+srv://jagdalesamruddhi23_db_user:1234@cluster0.3knuwwg.mongodb.net/student_report_system?appName=Cluster0
jwt.secret=studentReportSecretKey
jwt.expiration=86400000
